project_id = "ljaelokwxmwbgvfbjqlf"

[functions.create-initial-users]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true
